# Generated by Django 2.2.6 on 2020-06-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telefone', '0001_initial'),
        ('endereco', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Campo obrigatório como todos os que tiverem *', max_length=100, verbose_name='Numero do Telefone *')),
                ('cnpj', models.CharField(blank=True, help_text='Atenção: SOMENTE OS NÚMEROS', max_length=14, null=True, verbose_name='CNPJ')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='endereco.Endereco', verbose_name='Endereço')),
                ('telefone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telefone.Telefone', verbose_name='Telefone')),
            ],
            options={
                'db_table': 'Fornecedor',
            },
        ),
    ]
