# Generated by Django 2.2.6 on 2020-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Campo obrigatório como todos os que tiverem *', max_length=100, verbose_name='Numero do Telefone *')),
                ('codigo_area', models.IntegerField(verbose_name='Códio Area *')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição *')),
                ('pessoa', models.CharField(blank=True, max_length=100, verbose_name='Nome completo do contato')),
            ],
            options={
                'db_table': 'Telefone',
            },
        ),
    ]
