# Generated by Django 2.2.6 on 2020-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(help_text='Campo obrigatório como todos os que tiverem *', max_length=100, verbose_name='Rua *')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero *')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP *')),
                ('bairro', models.CharField(help_text='Campo obrigatório como todos os que tiverem *', max_length=100, verbose_name='Bairro *')),
            ],
            options={
                'db_table': 'Endereco',
            },
        ),
    ]
